services:
  # Backend (Slim Framework)
  backend:
    build:
      context: .
      dockerfile: Dockerfile
    volumes:
      - ./backend:/var/www/html
    ports:
      - "9000:9000"
    networks:
      - app-network
    depends_on:
      - db
    expose:
      - 9000 # Exponer el puerto 9000 para comunicaci칩n interna con Nginx

  # Servidor web (Nginx)
  webserver:
    image: nginx:alpine
    container_name: nginx
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf # Tu archivo de configuraci칩n de Nginx
      - ./backend:/var/www/html # El c칩digo del backend
    ports:
      - "8080:80" # Acceder치s a la API por el puerto 8080
    networks:
      - app-network
    depends_on:
      - backend

  # Base de Datos (MySQL)
  db:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpassword
      MYSQL_DATABASE: slimdb
      MYSQL_USER: slimuser
      MYSQL_PASSWORD: slimpassword
    volumes:
      - db_data:/var/lib/mysql
      - ./backend/docker-entrypoint-initdb.d:/docker-entrypoint-initdb.d
    ports:
      - "3306:3306"
    networks:
      - app-network

volumes:
  db_data:


networks:
  app-network:
